/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src;

import java.awt.Color;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Badar Muneer
 */
public class HireFireEmployee extends javax.swing.JPanel {

    /**
     * Creates new form HireFireEmployee
     */
    public HireFireEmployee() 
    {
        initComponents();
    }
    
    public void fillDeptBox()
    {
        try 
        {
            ResultSet rs=Employee.statement.executeQuery("SELECT * FROM DEPT");
            
            while(rs.next())
            {
                deptBox.addItem(rs.getInt("deptno")+"");
            }
        } catch (SQLException ex) 
        {
            JOptionPane.showMessageDialog(this, "Error","Error int loading Departments",JOptionPane.ERROR_MESSAGE);
            //Logger.getLogger(HireFireEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        empNumberField = new javax.swing.JTextField();
        firstNameField = new javax.swing.JTextField();
        lastNameField = new javax.swing.JTextField();
        maleRadioButton = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        skillBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        salaryField = new javax.swing.JTextField();
        hireButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        deptBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        searchTextField = new javax.swing.JTextField();
        fireButton = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Hire"));

        empNumberField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        empNumberField.setForeground(java.awt.Color.gray);
        empNumberField.setText("Employee Number");
        empNumberField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                empNumberFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                empNumberFieldFocusLost(evt);
            }
        });

        firstNameField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        firstNameField.setForeground(java.awt.Color.gray);
        firstNameField.setText("First Name");
        firstNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                firstNameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstNameFieldFocusLost(evt);
            }
        });

        lastNameField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lastNameField.setForeground(java.awt.Color.gray);
        lastNameField.setText("Last Name");
        lastNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lastNameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lastNameFieldFocusLost(evt);
            }
        });

        buttonGroup1.add(maleRadioButton);
        maleRadioButton.setSelected(true);
        maleRadioButton.setText("Male");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Female");

        skillBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Android Dev", "Web Dev", "Desktop Dev", "Marketing Exp", "iOs Dev" }));

        jLabel2.setText("Skill:");

        salaryField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        salaryField.setForeground(java.awt.Color.gray);
        salaryField.setText("Salary");
        salaryField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                salaryFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                salaryFieldFocusLost(evt);
            }
        });

        hireButton.setText("Hire");
        hireButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hireButtonActionPerformed(evt);
            }
        });

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Department:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(updateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hireButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(salaryField, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(skillBox, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lastNameField)
                                .addComponent(firstNameField)
                                .addComponent(empNumberField, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(maleRadioButton)
                                .addGap(44, 44, 44)
                                .addComponent(jRadioButton2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deptBox, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 15, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(empNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maleRadioButton)
                    .addComponent(jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deptBox, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(skillBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salaryField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hireButton)
                    .addComponent(updateButton))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Emp No:");

        searchTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        fireButton.setText("Fire");
        fireButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fireButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fireButton, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(searchTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(fireButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void empNumberFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_empNumberFieldFocusGained
        // TODO add your handling code here:
        
        if(empNumberField.getText().equals("Employee Number"))
        {
            empNumberField.setText("");
            empNumberField.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_empNumberFieldFocusGained

    private void empNumberFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_empNumberFieldFocusLost
        // TODO add your handling code here:
        
        if(empNumberField.getText().equals(""))
        {
            empNumberField.setText("Employee Number");
            empNumberField.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_empNumberFieldFocusLost

    private void firstNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstNameFieldFocusGained
        // TODO add your handling code here:
        
        if(firstNameField.getText().equals("First Name"))
        {
            firstNameField.setText("");
            firstNameField.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_firstNameFieldFocusGained

    private void firstNameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstNameFieldFocusLost
        // TODO add your handling code here:
        
        if(firstNameField.getText().equals(""))
        {
            firstNameField.setText("First Name");
            firstNameField.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_firstNameFieldFocusLost

    private void lastNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastNameFieldFocusGained
        // TODO add your handling code here:
        
        if(lastNameField.getText().equals("Last Name"))
        {
            lastNameField.setText("");
            lastNameField.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_lastNameFieldFocusGained

    private void lastNameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastNameFieldFocusLost
        // TODO add your handling code here:
        
        if(lastNameField.getText().equals(""))
        {
            lastNameField.setText("Last Name");
            lastNameField.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_lastNameFieldFocusLost

    private void salaryFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_salaryFieldFocusGained
        // TODO add your handling code here:
        if(salaryField.getText().equals("Salary"))
            
        {
            salaryField.setText("");
            salaryField.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_salaryFieldFocusGained

    private void salaryFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_salaryFieldFocusLost
        // TODO add your handling code here:
        
        if(salaryField.getText().equals(""))
        {
            salaryField.setText("Salary");
            salaryField.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_salaryFieldFocusLost

    private void hireButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hireButtonActionPerformed
        // TODO add your handling code here:
        
        if(empNumberField.getText().equals("Employee Number") || firstNameField.getText().equals("First Name") || lastNameField.getText().equals("Last Name"))
        {
            JOptionPane.showMessageDialog(this, "Some necessary Fields are empty", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Employee e=new Employee();
        try
        {
            e.setEmpNumber(Integer.parseInt(empNumberField.getText()));
        }catch(IllegalArgumentException ex)
        {
            JOptionPane.showMessageDialog(this, ex,"Error",JOptionPane.ERROR_MESSAGE);
        }
        e.setFirstName(firstNameField.getText());
        e.setLastName(lastNameField.getText());
        e.setGender(maleRadioButton.isSelected() ? "Male" : "Female");
        e.setSalary(Integer.parseInt(salaryField.getText()));
        e.setExpertise((String) skillBox.getSelectedItem());
        e.setDeptNo(Integer.parseInt((String)deptBox.getSelectedItem()));
        try 
        {
            Employee.statement.executeQuery("INSERT INTO EMP(EMPNO,F_NAME,L_NAME,GENDER,EXPERTISE,SAL,DEPTNO) VALUES("+e.getEmpNumber()+",'"+e.getFirstName()+"',"+"'"+e.getLastName()+"',"+"'"+e.getGender()+"',"+"'"+e.getExpertise()+"',"+e.getSal()+","+e.getDeptNo()+")");
            JOptionPane.showMessageDialog(this, "Inserted Successfully..","Insert",JOptionPane.INFORMATION_MESSAGE);
            
            empNumberField.setText("Employee Number");
            firstNameField.setText("First Name");
            lastNameField.setText("Last Name");
            salaryField.setText("Salary");
            
            empNumberField.setForeground(Color.GRAY);
            firstNameField.setForeground(Color.GRAY);
            lastNameField.setForeground(Color.GRAY);
            salaryField.setForeground(Color.GRAY);

        } catch (SQLException ex) {
            Logger.getLogger(HireFireEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_hireButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        if(empNumberField.getText().equals("Employee Number") || firstNameField.getText().equals("First Name") || lastNameField.getText().equals("Last Name"))
        {
            JOptionPane.showMessageDialog(this, "Some necessary Fields are empty", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Employee e=new Employee();
        try
        {
            e.setEmpNumber(Integer.parseInt(empNumberField.getText()));
        }catch(IllegalArgumentException ex)
        {
            JOptionPane.showMessageDialog(this, ex,"Error",JOptionPane.ERROR_MESSAGE);
        }
        e.setFirstName(firstNameField.getText());
        e.setLastName(lastNameField.getText());
        e.setGender(maleRadioButton.isSelected() ? "Male" : "Female");
        e.setSalary(Integer.parseInt(salaryField.getText()));
        e.setExpertise((String) skillBox.getSelectedItem());
        e.setDeptNo(Integer.parseInt((String)deptBox.getSelectedItem()));
        int oldEmpNumber=Integer.parseInt(JOptionPane.showInputDialog("Enter Old Emp Number:"));
        try 
        {
            Employee.statement.executeUpdate("UPDATE EMP SET EMPNO="+e.getEmpNumber()+" WHERE EMPNO="+oldEmpNumber);
            Employee.statement.executeUpdate("UPDATE EMP SET F_NAME='"+e.getFirstName()+"' WHERE EMPNO="+e.getEmpNumber());
            Employee.statement.executeUpdate("UPDATE EMP SET L_NAME='"+e.getLastName()+"' WHERE EMPNO="+e.getEmpNumber());
            Employee.statement.executeUpdate("UPDATE EMP SET GENDER='"+e.getGender()+"' WHERE EMPNO="+e.getEmpNumber());
            Employee.statement.executeUpdate("UPDATE EMP SET EXPERTISE='"+e.getExpertise()+"' WHERE EMPNO="+e.getEmpNumber());
            Employee.statement.executeUpdate("UPDATE EMP SET SAL="+e.getSal()+" WHERE EMPNO="+e.getEmpNumber());
            Employee.statement.executeUpdate("UPDATE EMP SET DEPTNO="+e.getDeptNo()+" WHERE EMPNO="+e.getEmpNumber());
            JOptionPane.showMessageDialog(this, "Updated Successfully..","Update",JOptionPane.INFORMATION_MESSAGE);
            
            empNumberField.setText("Employee Number");
            firstNameField.setText("First Name");
            lastNameField.setText("Last Name");
            salaryField.setText("Salary");
            
            empNumberField.setForeground(Color.GRAY);
            firstNameField.setForeground(Color.GRAY);
            lastNameField.setForeground(Color.GRAY);
            salaryField.setForeground(Color.GRAY);
        } catch (SQLException ex) 
            {
                JOptionPane.showMessageDialog(this, ex);
                ex.printStackTrace();
                //Logger.getLogger(HireFireEmployee.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void fireButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fireButtonActionPerformed
        // TODO add your handling code here:
        
        if(searchTextField.getText().equals("")) return;
       int empNo=Integer.parseInt(searchTextField.getText());
        try 
        {
            boolean isDeleted=Employee.statement.execute("DELETE FROM EMP WHERE EMPNO="+empNo);
            
            if(!isDeleted)
                JOptionPane.showMessageDialog(this, "Deleted Successfull..","Delete",JOptionPane.INFORMATION_MESSAGE);
            else
                JOptionPane.showMessageDialog(this, "Failed To Delete","Delete",JOptionPane.WARNING_MESSAGE);
            
            searchTextField.setText("");
        } catch (SQLException ex) 
        {
            Logger.getLogger(HireFireEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_fireButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> deptBox;
    private javax.swing.JTextField empNumberField;
    private javax.swing.JButton fireButton;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JButton hireButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JRadioButton maleRadioButton;
    private javax.swing.JTextField salaryField;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JComboBox<String> skillBox;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
