/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src;

import java.awt.Color;
import java.awt.CardLayout;
/**
 *
 * @author Badar Muneer
 */
public class HomeScreen extends javax.swing.JFrame {

    /**
     * Creates new form HomeScreen
     */
    private final HomeScreenDisplay homeScreenDisplay;
    private final ProjectMainScreen projectScreen;
    private final EmployeeScreen employeeScreen;
    private final DepartmentScreen departmentScreen;
    //private EmployeeScreen employeeScreen;
    private boolean isMenuOpened;
    public HomeScreen() 
    {
        projectScreen=new ProjectMainScreen();
        homeScreenDisplay=new HomeScreenDisplay();
        employeeScreen=new EmployeeScreen();
        departmentScreen=new DepartmentScreen();
        //employeeScreen=new EmployeeScreen();
        initComponents();
        //HomeScreenDisplay display= new HomeScreenDisplay();
        cardDisplayPanel.add(homeScreenDisplay,"homeScreen");
        cardDisplayPanel.add(projectScreen,"projectMainScreen");
        cardDisplayPanel.add(employeeScreen,"employeeScreen");
        cardDisplayPanel.add(departmentScreen,"departmentScreen");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        sideMenuPanel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        employeeMenuLabel = new javax.swing.JLabel();
        deptLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        projectLable = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        homeLabel = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        headingLabel = new javax.swing.JLabel();
        menuLabelIcon = new javax.swing.JLabel();
        cardDisplayPanel = new javax.swing.JPanel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee Management System");

        mainPanel.setBackground(new java.awt.Color(51, 255, 204));

        sideMenuPanel.setBackground(new java.awt.Color(204, 0, 153));
        sideMenuPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        sideMenuPanel.setPreferredSize(new java.awt.Dimension(0, 530));

        employeeMenuLabel.setBackground(new java.awt.Color(242, 242, 242));
        employeeMenuLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        employeeMenuLabel.setForeground(new java.awt.Color(255, 255, 255));
        employeeMenuLabel.setText("Employees");
        employeeMenuLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employeeMenuLabelMouseClicked(evt);
            }
        });

        deptLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        deptLabel.setForeground(new java.awt.Color(255, 255, 255));
        deptLabel.setText("Departments");
        deptLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deptLabelMouseClicked(evt);
            }
        });

        projectLable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        projectLable.setForeground(new java.awt.Color(255, 255, 255));
        projectLable.setText("Projects");
        projectLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                projectLableMouseClicked(evt);
            }
        });

        homeLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        homeLabel.setForeground(new java.awt.Color(255, 255, 255));
        homeLabel.setText("Home");
        homeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout sideMenuPanelLayout = new javax.swing.GroupLayout(sideMenuPanel);
        sideMenuPanel.setLayout(sideMenuPanelLayout);
        sideMenuPanelLayout.setHorizontalGroup(
            sideMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sideMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sideMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sideMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(projectLable, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(sideMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                                .addComponent(employeeMenuLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(deptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator4))
                    .addComponent(homeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sideMenuPanelLayout.setVerticalGroup(
            sideMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideMenuPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(homeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(employeeMenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(projectLable, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(310, Short.MAX_VALUE))
        );

        headingLabel.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        headingLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/employee.png"))); // NOI18N
        headingLabel.setText("Employee Management System");

        menuLabelIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/menu.png"))); // NOI18N
        menuLabelIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLabelIconMouseClicked(evt);
            }
        });

        cardDisplayPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuLabelIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 534, Short.MAX_VALUE)
                .addComponent(headingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(207, 207, 207))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(sideMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cardDisplayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 866, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(sideMenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuLabelIcon)
                    .addComponent(headingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardDisplayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuLabelIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLabelIconMouseClicked
        // TODO add your handling code here:
        if(!isMenuOpened)
        {
            for(int i=10; i<=260; i+=10)
            {
                sideMenuPanel.setSize(i,this.getHeight());
            }
            isMenuOpened=true;
        }
        
        else
        {
            for(int i=200; i>=0; i-=10)
            {
                sideMenuPanel.setSize(i,this.getHeight());
            }
            isMenuOpened=false;
        }
    }//GEN-LAST:event_menuLabelIconMouseClicked

    private void homeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLabelMouseClicked
        // TODO add your handling code here:
        CardLayout card=(CardLayout)cardDisplayPanel.getLayout();
        card.show(cardDisplayPanel,"homeScreen");
        this.homeScreenDisplay.setLabelsText();
        
        
       // this.cardLayout.show(cardDisplayPanel,"HomeScreen");
    }//GEN-LAST:event_homeLabelMouseClicked

    private void employeeMenuLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeMenuLabelMouseClicked
        // TODO add your handling code here:
        
        CardLayout card=(CardLayout)cardDisplayPanel.getLayout();
        card.show(cardDisplayPanel,"employeeScreen");
    }//GEN-LAST:event_employeeMenuLabelMouseClicked

    private void projectLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_projectLableMouseClicked
        // TODO add your handling code here:
        
        CardLayout card=(CardLayout)this.cardDisplayPanel.getLayout();
        card.show(cardDisplayPanel, "projectMainScreen");
    }//GEN-LAST:event_projectLableMouseClicked

    private void deptLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deptLabelMouseClicked
        // TODO add your handling code here:
        
        CardLayout card=(CardLayout)cardDisplayPanel.getLayout();
        card.show(cardDisplayPanel, "departmentScreen");
    }//GEN-LAST:event_deptLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cardDisplayPanel;
    private javax.swing.JLabel deptLabel;
    private javax.swing.JLabel employeeMenuLabel;
    private javax.swing.JLabel headingLabel;
    private javax.swing.JLabel homeLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel menuLabelIcon;
    private javax.swing.JLabel projectLable;
    private javax.swing.JPanel sideMenuPanel;
    // End of variables declaration//GEN-END:variables
}
