/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src;
import java.awt.Color;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
/**
 *
 * @author Badar Muneer
 */
public class IosDepart extends javax.swing.JPanel {

    /**
     * Creates new form IosDepart
     */
    public IosDepart() {
        initComponents();
    }
    
    public void showChart()
    {
        LocalDate date=LocalDate.now();
       DefaultCategoryDataset dcd=new DefaultCategoryDataset();
      
       
        try 
        {
            ResultSet rs=Project.statement.executeQuery("SELECT EMPNO,COUNT(EMPNO) FROM PROS WHERE TYPE_ID=444 AND EXTRACT(MONTH FROM COMP_DATE)="+date.getMonthValue()+" GROUP BY EMPNO");
            
            while(rs.next())
            {
                dcd.setValue(rs.getInt(2),"Projects", rs.getInt(1)+"");
            }
        } 
        catch (SQLException ex) 
        {
            JOptionPane.showMessageDialog(this,"Error");
            ex.printStackTrace();
        }
        
        JFreeChart chart=ChartFactory.createBarChart("iOS Employee Report","Emp Number","Projects",dcd,PlotOrientation.VERTICAL,true,true,false);
        CategoryPlot plot=chart.getCategoryPlot();
        plot.setRangeGridlinePaint(Color.RED);
        
//        ChartFrame frame=new ChartFrame("Android Employee Report",chart,true);
//        
//        frame.setVisible(true);
//        frame.setSize(300,300);
//        
        ChartPanel panel=new ChartPanel(chart);
        displayChartPanel.add(panel);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayChartPanel = new javax.swing.JPanel();

        displayChartPanel.setLayout(new javax.swing.BoxLayout(displayChartPanel, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(displayChartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(displayChartPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel displayChartPanel;
    // End of variables declaration//GEN-END:variables
}
